### PR TITLE
Missing Reset View and Func

### PR DESCRIPTION
**Pull request by saroar**
Add a missing view and func for resetPassword function

### CODE REVIEW

**Comment by kjessup** [comment]
Thanks for this. I have a couple questions:
Does this break existing code in any way? In particular:
• Schema/Account.swift adds `try this.find(["username": username])`

Additionally, views/resetPasswordComplete.mustache outputs several bits of info using the moustache unencoded tags: {{{ blah }}}
It's ultimately un-safe for HTML. Is there a reason for that?

Maybe @iamjono can look this over as well.

**Comment by saroar** [comment]
• Schema/Account.swift adds try this.find(["username": username])
about this I will remove it we don't need this I fixed another way i think

**Comment by saroar** [comment]
@kjessup can you check this `{{>blabla}}` it everywhere in this inside `view` i think its normal also it not 3 times `{{{` it two times `{{`

**Comment by saroar** [comment]
so i am going to close this pull request and open new one becz i remove this `try this.find(["username": username])`

**Pull request closed without merging**
